CREATE CONSTRAINT concept_name IF NOT EXISTS FOR (c:Concept) REQUIRE c.name IS UNIQUE;
CREATE CONSTRAINT student_id IF NOT EXISTS FOR (s:Student) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT misconception_name IF NOT EXISTS FOR (m:Misconception) REQUIRE m.name IS UNIQUE;

CREATE (c1:Concept {name: "一元一次方程", subject: "数学", grade: "初一", difficulty: 0.3})
CREATE (c2:Concept {name: "一元二次方程", subject: "数学", grade: "初三", difficulty: 0.5})
CREATE (c3:Concept {name: "二次函数", subject: "数学", grade: "初三", difficulty: 0.6})
CREATE (c4:Concept {name: "函数图像变换", subject: "数学", grade: "初三", difficulty: 0.65})
CREATE (c5:Concept {name: "不等式", subject: "数学", grade: "初二", difficulty: 0.4})
CREATE (c6:Concept {name: "绝对值", subject: "数学", grade: "初一", difficulty: 0.25})
CREATE (c7:Concept {name: "因式分解", subject: "数学", grade: "初二", difficulty: 0.45})
CREATE (c8:Concept {name: "配方法", subject: "数学", grade: "初三", difficulty: 0.55})
CREATE (c9:Concept {name: "判别式", subject: "数学", grade: "初三", difficulty: 0.5})
CREATE (c10:Concept {name: "韦达定理", subject: "数学", grade: "初三", difficulty: 0.6})
CREATE (c11:Concept {name: "极限", subject: "数学", grade: "高三", difficulty: 0.75})
CREATE (c12:Concept {name: "导数", subject: "数学", grade: "高三", difficulty: 0.8})
CREATE (c13:Concept {name: "定积分", subject: "数学", grade: "高三", difficulty: 0.85})
CREATE (c14:Concept {name: "不定积分", subject: "数学", grade: "高三", difficulty: 0.85})
CREATE (c15:Concept {name: "微积分基本定理", subject: "数学", grade: "高三", difficulty: 0.9})

CREATE (c7)-[:HAS_PREREQUISITE]->(c2)
CREATE (c1)-[:HAS_PREREQUISITE]->(c5)
CREATE (c1)-[:HAS_PREREQUISITE]->(c6)
CREATE (c2)-[:HAS_PREREQUISITE]->(c3)
CREATE (c2)-[:HAS_PREREQUISITE]->(c8)
CREATE (c8)-[:HAS_PREREQUISITE]->(c3)
CREATE (c2)-[:HAS_PREREQUISITE]->(c9)
CREATE (c9)-[:HAS_PREREQUISITE]->(c10)
CREATE (c3)-[:HAS_PREREQUISITE]->(c4)
CREATE (c11)-[:HAS_PREREQUISITE]->(c12)
CREATE (c12)-[:HAS_PREREQUISITE]->(c14)
CREATE (c14)-[:HAS_PREREQUISITE]->(c13)
CREATE (c13)-[:HAS_PREREQUISITE]->(c15)
CREATE (c12)-[:HAS_PREREQUISITE]->(c15)

CREATE (m1:Misconception {name: "混淆顶点式与一般式", freq: 0.35, root: "配方法掌握不足"})
CREATE (m2:Misconception {name: "开口方向判断错误", freq: 0.25, root: "系数正负理解偏差"})
CREATE (m3:Misconception {name: "求根公式记忆错误", freq: 0.30, root: "公式推导过程不熟"})
CREATE (m4:Misconception {name: "忽略判别式判断", freq: 0.40, root: "实数根条件理解缺失"})
CREATE (m5:Misconception {name: "符号混淆", freq: 0.45, root: "推导过程不熟练"})
CREATE (m6:Misconception {name: "混淆极限不存在与无穷大", freq: 0.35, root: "极限定义理解不足"})
CREATE (m7:Misconception {name: "链式法则应用错误", freq: 0.40, root: "复合函数分解能力弱"})
CREATE (m8:Misconception {name: "混淆导数与原函数关系", freq: 0.30, root: "导数几何意义理解不足"})
CREATE (m9:Misconception {name: "遗漏积分常数C", freq: 0.50, root: "不定积分概念理解偏差"})
CREATE (m10:Misconception {name: "上下限代入错误", freq: 0.35, root: "牛顿莱布尼茨公式不熟"})
CREATE (m11:Misconception {name: "十字相乘法符号错误", freq: 0.35, root: "符号运算粗心"})
CREATE (m12:Misconception {name: "配方步骤遗漏", freq: 0.40, root: "完全平方公式不熟"})

CREATE (c3)-[:HAS_MISCONCEPTION]->(m1)
CREATE (c3)-[:HAS_MISCONCEPTION]->(m2)
CREATE (c2)-[:HAS_MISCONCEPTION]->(m3)
CREATE (c2)-[:HAS_MISCONCEPTION]->(m4)
CREATE (c10)-[:HAS_MISCONCEPTION]->(m5)
CREATE (c11)-[:HAS_MISCONCEPTION]->(m6)
CREATE (c12)-[:HAS_MISCONCEPTION]->(m7)
CREATE (c12)-[:HAS_MISCONCEPTION]->(m8)
CREATE (c14)-[:HAS_MISCONCEPTION]->(m9)
CREATE (c13)-[:HAS_MISCONCEPTION]->(m10)
CREATE (c7)-[:HAS_MISCONCEPTION]->(m11)
CREATE (c8)-[:HAS_MISCONCEPTION]->(m12)
